#to import numpy library
# numpy indexing and slicing..
import numpy as np
n2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n2)
print(n2.ndim)
# To accesss the numpy array elements
# 1.to print the first row elements
print(n2[0])
#2> To print the last row elements
print(n2[-1])
#3. To print the specific element
print(n2[1,0])
# 4.To print the alternative rows..
print(n2[::2])
# 5.To print the specific coliumn elements..
print(n2[:,[1]])

In [2]:
#to import numpy library
# numpy indexing and slicing..
import numpy as np
n2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(n2.ndim)


2


In [4]:
print(n2.ndim)


2


In [5]:
# To accesss the numpy array elements
# 1.to print the first row elements
print(n2[0])


[1 2 3]


In [7]:
#2> To print the last row elements
print(n2[-1])
#3. To print the specific element
print(n2[1,0])
# 4.To print the alternative rows..
print(n2[::2])
# 5.To print the specific coliumn elements..
print(n2[:,[1]])

[7 8 9]
4
[[1 2 3]
 [7 8 9]]
[[2]
 [5]
 [8]]


In [8]:
#boolean indexing and fancy indexing:

print(n2)
# example on boolean indexing..
# To print the even values..
print(n2%2==0)
#example of fancy indexing..
print(n2[n2%2==0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


In [ ]:
### array manipulations:
- reshape: To convert the 1-d array to n-d array.
    suntax:
            numpy_1d_array.reshape(rows,columns)
            - number of 1-d elements size == rows*columns
- resize

In [11]:
a=np.array([[1,2],[3,4]])
print(a)
b=np.array([[1,1],[2,2]])
print('apply vstack:\n',np.vstack((a,b)))
print('apply hstack:\n',np.hstack((a,b)))

[[1 2]
 [3 4]]
apply vstack:
 [[1 2]
 [3 4]
 [1 1]
 [2 2]]
apply hstack:
 [[1 2 1 1]
 [3 4 2 2]]


In [ ]:
print(n2)
n2=n2.ravel()
print(n2)